2
htmlacademy-univer-javascript-1/2579361-kekstagram-5 pull request #3
Opened 2024-11-20 13:45 UTC by danillavrentev

2024-11-22 07:50 UTC, dimohqa requested changes

2024-11-22 07:50 UTC, dimohqa commented on js/functions.js
> +// const strCheck = function(str) {
А почему все функции закомментированы? Давай поправим, иначе подсветка кода не видна. Да и в PR при работе в комментариях лучше не оставлять код, иначе потом никто не вспомнит почему он закомментирован (это рекомендация на будущее)

2024-11-22 07:50 UTC, dimohqa commented on js/functions.js
> +// }
> Обратите внимание, что для решения этой задачи можно использовать if/else или тернарный оператор, однако это избыточно, так как операция сравнения сама по себе возвращает нужный нам результат.

В сносках задания было такое интересное уточнение. Подумай как стоит изменить текущую функцию, чтобы упростить код.

2024-11-22 07:50 UTC, dimohqa commented on js/functions.js
> +// const strCheck2 = function(str,length){
Из названия функции не понятно что именно она делает, а точнее как проверяет эту строку. Давай подумаем над неймингом. Краткость круто, но важнее всего передать смысл действия.

2024-11-22 07:50 UTC, dimohqa commented on js/functions.js
> +let str;
Тут тебе github подсказывает, что ты инициализировал переменную, которая нигде не используется. Постарайся проверять код перед отправкой PR, а затем еще раз самостоятельно проверять его уже в github. Это упростит и ускорит проверку твоих заданий как для преподователя, так и для тебя самого.

2024-11-22 07:50 UTC, dimohqa commented on js/functions.js
> +  return str.toUpperCase().replaceAll(' ','').split('').reverse().join('') === str.toUpperCase().replaceAll(' ','').split('').join('') ? 'Эта строка палиндром': 'Не является палиндромом';
В постановке задачи ответом функции является булево значение, а не строка

2024-11-22 07:50 UTC, dimohqa commented on js/functions.js
> +  return str.toUpperCase().replaceAll(' ','').split('').reverse().join('') === str.toUpperCase().replaceAll(' ','').split('').join('') ? 'Эта строка палиндром': 'Не является палиндромом';
Зачем делать `.split('').join('')` при повторном преобразовании?

2024-11-22 07:50 UTC, dimohqa commented on js/functions.js
> +  return str.toUpperCase().replaceAll(' ','').split('').reverse().join('') === str.toUpperCase().replaceAll(' ','').split('').join('') ? 'Эта строка палиндром': 'Не является палиндромом';
Очень круто, когда в коде операции над одними и теми же данными выполняются единожды. Их результат можно записывать в переменные. 

Например, ты 2 раза применяешь нормализацию к строке: `str.toUpperCase().replaceAll(' ','')`. Давай подумаем как изменить код, чтобы упростить его чтение.

2024-11-22 07:50 UTC, dimohqa commented on js/functions.js
> +//     }
Интересное решение и хорошее оформление функции. Сам догадался до использования лексикографического порядка в сравнении?

2024-11-24 05:14 UTC, danillavrentev commented on js/functions.js
> +// const strCheck = function(str) {
Хорошо, совсем забыл про это )

2024-11-25 13:48 UTC, danillavrentev commented on js/functions.js
> +// }
Решил пример 1 по-другому

2024-11-25 13:49 UTC, danillavrentev commented on js/functions.js
> +// const strCheck2 = function(str,length){
Поправил имена функции, сделал более понятное

2024-11-25 13:54 UTC, danillavrentev commented on js/functions.js
> +  return str.toUpperCase().replaceAll(' ','').split('').reverse().join('') === str.toUpperCase().replaceAll(' ','').split('').join('') ? 'Эта строка палиндром': 'Не является палиндромом';
Убрал два метода дял повторного преобразования. Действительно смысла от них нет

2024-11-25 13:58 UTC, danillavrentev commented on js/functions.js
> +  return str.toUpperCase().replaceAll(' ','').split('').reverse().join('') === str.toUpperCase().replaceAll(' ','').split('').join('') ? 'Эта строка палиндром': 'Не является палиндромом';
Создал две новые переменные послек преобразования методами.

2024-11-25 14:00 UTC, danillavrentev commented on js/functions.js
> +//     }
Честно подсмотрел немного👀

2024-11-25 14:16 UTC, danillavrentev commented
ESLint не пропускает

2024-11-27 11:58 UTC, merged